### ISSUE TITLE
Epic - View individual book details

### ISSUE THREAD

**Issue by wendybaum** [wendybaum/Bookly#3]
## User Story

As a user I would like to be able to view details about each specific book in my Google Books 'To Read' Bookshelf.

## Acceptance Criteria

- [ ] The user's Google Books 'To Read' Bookshelf is displayed
- [ ]  A thumbnail of the book cover is shown
- [ ]  The book title is shown
- [ ] The books' link to free version online if it exists is shown
- [ ]  The ISBN is shown
